### ISSUE TITLE
http to https redirect

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cache-clear#5]
It looks like the http to https redirect isn't setup? Kathryn had issues going directly to cache.bethel.edu for the first time.

@josiahtillman want to take a look at this sometime.

**Comment by phg49389** [comment]
I just checked this; I got the expected 301 redirect from http => https. Also, the vhosts seem to be in order on wlp-fn2187.

Are there any other details about Kathryn's experience? This feels like a fluke, rather than an issue.

**Comment by c-schwarze** [comment]
Both Kathryn and one of the other students was having issues

**Comment by phg49389** [comment]
Wonder if it's specific to that computer, since the two affected were both Emily's student workers?

**Comment by phg49389** [comment]
I talked with Emily today; it sounds like Cassidy is using the right computer, but Kathryn used the left. Emily is going to ask Cassidy to try again when Cassidy comes to work tomorrow morning.

**Comment by phg49389** [comment]
I just visited Emily and her student worker, had them try the following:

- Visiting cache.bethel.edu in both Chrome and Safari returned an ERR_CONNECTION_REFUSED
- There wasn't anything in /etc/hosts
- dig cache.bethel.edu succesfully resolved to wlp-fn2187

I'm going to look in Cache's Apache access_log to see if it told us why it's denying the connection

**Comment by phg49389** [comment]
The issue was that the server that hosted cache.bethel.edu, wlp-fn2187, had a firewall rule that disallowed the Bethel IP-space from accessing port 80, but not port 443. The reason Caleb and I weren't having issues was because there was a specific rule allowing the Web Services team.

John kindly allowed port 80, and now it works for Morgan. And by extension everyone else. However, since I just implemented the IAM Group check, that should be fine.
